### ISSUE TITLE
Could you tell me where can i download the LHDL dataset?

### ISSUE THREAD

**Issue by HongWei8506** [modenaxe/3d-muscles#1]

**Comment by HongWei8506** [comment]
I want another part models, i.e., head or arm. Thanks!

**Comment by modenaxe** [comment]
Hi @HsuHungWei, what are you looking for exactly?
The LHDL dataset only has bone geometries for upper body, no muscle data.

**Comment by HongWei8506** [comment]
I want make a model that can describe the whole facial muscle.  I have already the MRI pics of the head, but I have not idea the next step what I do. When I see the your paper, the method of the musculoskeletal models is what I need. So, If you can tell me which method can do or which tool/software can do, I will appreciate.

**Comment by modenaxe** [comment]
@HsuHungWei modelling of that part of the body is outside my field of expertise. I am aware of work done at the Auckland Bioengineering Institute, e.g. [this paper](https://doi.org/10.1016/j.finel.2013.08.002), using cmiss (finite element analysis) and maybe you can find something relevant searching for application of [ArtiSynth](https://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.715.3236&rep=rep1&type=pdf), which combines multibody and finite element models, but I would not be able to advise you much further I am afraid .

**Comment by HongWei8506** [comment]
ok, thanks again!
