### ISSUE TITLE
Biceps data

### ISSUE THREAD

**Issue by Justarone** [modenaxe/3d-muscles#2]
Hello! Sorry in advance if the question is silly.

About me: I have tiny project with simple biceps model, and my scientific director requested to compare geometry parameters of my model with real muscle (but I didn't find data for real biceps) or another biceps model (which gives information about it's geometry parameters)

Question: Do you have any data to construct biceps model? I can't understand it from your datasets names and can't check it in opensim, cause I just requested access to installer today, and need to wait 72 hours.

Thank you in advance!

**Comment by modenaxe** [comment]
Hi @Justarone this repository does not include data for the biceps muscle but only hip spanning muscles, I suggest you to look for this information on the [OpenSim model library](https://simtk-confluence.stanford.edu/display/OpenSim/Musculoskeletal+Models). 
The OpenSim installer is freely available [here](https://simtk.org/projects/opensim) (needs registration). 

I hope this helps.

**Comment by Justarone** [comment]
Thank you for your answer!

I am a little bit confused: I read your README and some parts of doc, and didn't understand 2 moments:

Is there only moment arm as geometry characteristic?

Can I import data for my models (if I get freely available biceps) with your matlab script (in readme you use your files(?), can I generate them somehow(?))?

**Comment by modenaxe** [comment]
Hi, this repository has currently the **only** aim to allow researchers to reproduce the results of the listed publication, for which the models are provided. The software to generate the lines of action from the muscle surfaces is still under development and will be released in the future.
